### ISSUE TITLE
`get_player_market_values()` not working

### ISSUE THREAD

**Issue by Fefo20** [JaseZiv/worldfootballR#83] opened 2022-01-18 00:10 UTC
Hello,
I'm getting this error message when using `get_player_market_values():` 

"Error in open.connection(x, "rb") :    SSL certificate problem: certificate has expired."

Thanks in advance!

**Comment by JaseZiv** [comment] 2022-01-18 00:21
Hi there,

See this Twitter thread (and closed issue) for the reasons for this error:

https://twitter.com/jaseziv/status/1463088586190843904?s=21

**Comment by Fefo20** [comment] 2022-01-18 01:57
Thanks! So it looks like the problem is on my side.

I'm also getting an error when using league_url argument in the same function. 
For example:

`get_player_market_values(league_url = 'https://www.transfermarkt.com/premier-league/startseite/wettbewerb/GB1')`
Error in get_player_market_values(league_url = "https://www.transfermarkt.com/premier-league/startseite/wettbewerb/GB1") : 
  object 'league_page' not found 

I couldn't sort the previous one with the links in the closed issue, but I will look into it and notify you if I find a solution.

I'm using macOS Mojave version 10.14.4, R 4.0.2 and worldfootballR 0.4.9 .

**Comment by JaseZiv** [comment] 2022-01-18 03:16
Yeah it might be the OS version... I had no issues running the code you've provided running on Big Sur.

Let me know how you go.

**Comment by sos-dewan** [comment] 2022-01-23 05:37
Hello,

I'm also having trouble with this function but mine is a bit different. It does not show _"Error in open.connection(x, "rb") : SSL certificate problem: certificate has expired."_ but all the "**player_name**", "**player_dob**" and "**player_age**" is returned as NA. And the following warning message is shown.

_Warning messages:
1: Expected 4 pieces. Missing pieces filled with `NA` in 737 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
2: Problem with `mutate()` column `Year`.
i `Year = as.numeric(.data$Year)`.
i NAs introduced by coercion 
3: Problem with `mutate()` column `player_dob`.
i `player_dob = lubridate::ymd(paste(.data$Year, .data$Month, .data$Day, sep = "-"))`.
i All formats failed to parse. No formats found._

I'm using Windows 10 Home 64-bit (10.0 Build 18363)
RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08)
worldfootballR_0.4.9

**Comment by JaseZiv** [comment] 2022-01-23 05:46
Thanks for submitting this @sos-dewan.

This problem you're having was caused by HTML changes on the site, but has been fixed in the dev version.

Update your version of worldfootballR by using `devtools::install_github("JaseZiv/worldfootballR")`.

Let me know if there's any more issues.

**Comment by sos-dewan** [comment] 2022-01-23 05:50
> Hello,
> 
> I'm also having trouble with this function but mine is a bit different. It does not show _"Error in open.connection(x, "rb") : SSL certificate problem: certificate has expired."_ but all the "**player_name**", "**player_dob**" and "**player_age**" is returned as NA. And the following warning message is shown.
> 
> _Warning messages: 1: Expected 4 pieces. Missing pieces filled with `NA` in 737 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 2: Problem with `mutate()` column `Year`. i `Year = as.numeric(.data$Year)`. i NAs introduced by coercion 3: Problem with `mutate()` column `player_dob`. i `player_dob = lubridate::ymd(paste(.data$Year, .data$Month, .data$Day, sep = "-"))`. i All formats failed to parse. No formats found._
> 
> I'm using Windows 10 Home 64-bit (10.0 Build 18363) RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) worldfootballR_0.4.9

This problem was solved by uninstalling the previous version and installing directly from the github using 
_remotes::install_github("JaseZiv/worldfootballR")_. Might have been the other dependencies were outdated which created conflict with this library.

**Closed** 2022-01-23 05:53 UTC
