### ISSUE TITLE
get_season_team_stats() not working for PL, LaLiga and Bundesliga 2020/21 anymore

### ISSUE THREAD

**Issue by ChrisH1997** [JaseZiv/worldfootballR#48] opened 2021-08-11 14:28 UTC
`get_season_team_stats(c("ENG", "ESP", "ITA", "GER", "FRA"), "M", c(2018:2021), "1st", "passing")` used to work for all categories. Now it says 
`Scraping season standard stats
NOTE: Stat Type 'standard' is not found for this league season. Check https://fbref.com/en/comps/9/Premier-League-Stats to see if it exists.
NOTE: Stat Type 'standard' is not found for this league season. Check https://fbref.com/en/comps/12/La-Liga-Stats to see if it exists.
NOTE: Stat Type 'standard' is not found for this league season. Check https://fbref.com/en/comps/20/Bundesliga-Stats to see if it exists.`
The result includes all four seasons for Ligue 1 and Serie A, but only 2018-2020 for PL, LaLiga and BL.

**Comment by JaseZiv** [comment] 2021-08-13 01:41
Thanks for bringing this one up.

This has been fixed now - it was caused by the new seasons about to start getting a new URL structure on fbref.

Reach out if the issue persists.

**Closed by JaseZiv** 2021-08-13 01:41 UTC

**Comment by ChrisH1997** [comment] 2021-08-18 10:02
Hey, it seems as if now the same happened for Serie A season 2020/21.

**Comment by JaseZiv** [comment] 2021-08-18 21:06
@ChrisH1997 Just pushed a new version of the seasons/leagues metadata this package uses and it should fix the Serie A issue you're having.

Reach out if this isn't the case.

Thanks again
